# This step is to sign-in to Azure to run tests from GitHub Action workflow.
# Choose how to set up authentication to Azure from GitHub Actions. This is one example.
name: Playwright Tests (Playwright Workspaces)
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: # Required when using Microsoft Entra ID to authenticate
  id-token: write
  contents: read

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Azure with AzPowershell (enableAzPSSession true)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }} # GitHub Open ID connect values copied in previous steps
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Install dependencies
        working-directory: / # update accordingly
        run: npm ci

      - name: Run Playwright tests
        working-directory: / # update accordingly
        env:
          # Regional endpoint for Playwright Workspaces
          PLAYWRIGHT_SERVICE_URL: ${{ secrets.PLAYWRIGHT_SERVICE_URL }}
        run: npx playwright test -c playwright.service.config.ts --workers=1

      - name: Upload Playwright report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: /playwright-report/ # update accordingly
          retention-days: 10
